# Используем официальный образ Node.js как основу
FROM node:20-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /front

# Копируем только package.json и package-lock.json (или yarn.lock)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --production

# Копируем все остальные файлы проекта
COPY . .

# Строим проект Next.js
RUN npm run build

# Экспонируем порт приложения
EXPOSE 3000

# Запускаем сервер Next.js в режиме production
CMD ["npm", "start"]

